### ISSUE TITLE
Not seeing anything in DataDog

### ISSUE THREAD

**Issue by bennichols** [apiaryio/heroku-datadog-drain-golang#15]
Hi, I'm trying to get this running, and it seems everything is working properly, however nothing is showing up on DataDog. I set the HEROKU_APP_NAME and DATADOG_API_KEY as specified in the buildpack as well, but still no dice. Is there something I'm missing?

**Comment by w-vi** [comment]
Hi @bennichols sorry for late reply have you had any success or can I help somehow?

**Comment by abtris** [comment]
Maybe missing `STATSD_URL: localhost:8125`, we omitted protocol in golang version.

**Comment by abtris** [comment]
We updated readme, I hope this helps. If not please reopen this ticket.
