### ISSUE TITLE
Error when parsing "path" or "host" that have numbers

### ISSUE THREAD

**Issue by ghantoos** [apiaryio/heroku-datadog-drain-golang#36]
Hi,

It looks like the the `path` and `host` keys are parsed as if they were regular number metrics, which means that they are cut at the last digit, and then ignore the rest of the string. This works well with time metrics like `11ms`.

You can easily reproduce by changing the `path` in `server_test.go` from `path="/users"` to something like `path="/u1sers"` which should return `path:/u1`.

I was able to correct this by applying a patch on `logproc.go`:
```
diff --git a/logproc.go b/logproc.go
index ff7bd80..6390bac 100644
--- a/logproc.go
+++ b/logproc.go
@@ -28,7 +28,7 @@ var dynoNumber *regexp.Regexp = regexp.MustCompile(`\.\d+$`)
 func (lm *logMetrics) HandleLogfmt(key, val []byte) error {

        i := bytes.LastIndexFunc(val, isDigit)
-       if i == -1 {
+       if i == -1 || string(key) == "path" || string(key) == "host" {
                lm.metrics[string(key)] = logValue{string(val), ""}
        } else {
                lm.metrics[string(key)] = logValue{string(val[:i+1]), string(val[i+1:])}
```

I could send you a PR, unless you have another way to better correct this.

**Comment by abtris** [comment]
Yes, all metrics are parsed as numbers. Path and host are good as tags not as metrics.
