### ISSUE TITLE
Collect metrics from several applications

### ISSUE THREAD

**Issue by bronislav** [apiaryio/heroku-datadog-drain-golang#37]
Is there are a way to mark metrics with some tag to separate them from other application/environment?

**Comment by w-vi** [comment]
That's what we do, so can you please elaborate a bit more what exactly you need? Is it custom metrics?

**Comment by w-vi** [comment]
You can set tags per application https://github.com/apiaryio/heroku-datadog-drain-golang#configuration

**Comment by bronislav** [comment]
Sorry, I missed that metric. Closed.

**Comment by w-vi** [comment]
No worries, documentation is really not there ...
