### ISSUE TITLE
Issue pushing to Heroku Buildpack Detection

### ISSUE THREAD

**Issue by phrohike** [apiaryio/heroku-datadog-drain-golang#45]
Hello, 

Im getting an error when trying to push to Heroku: 

```
remote: -----> Failed to detect app matching https://codon buildpacks.s3.amazonaws.com/buildpacks/heroku/go.tgz buildpack
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
```

Do I need more than the heroku/go buildpack? 

Thank you. 

Keith

**Comment by w-vi** [comment]
Yes, the usual go buildpack is not enough see [Get Started](https://github.com/apiaryio/heroku-datadog-drain-golang#get-started) in the README.
